IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'FI_SP_ConsCliente_V2')
    DROP PROCEDURE FI_SP_ConsCliente_V2;
GO
CREATE PROC FI_SP_ConsCliente_V2
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID, CPF FROM CLIENTES WITH(NOLOCK)
	ELSE
		SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID, CPF FROM CLIENTES WITH(NOLOCK) WHERE ID = @ID
END